/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Database_access.DaoEquipment;
import Database_access.DaoUser;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author famil
 */
public class ListMembers extends javax.swing.JPanel {

    /**
     * Creates new form ListMembers
     */
    public ListMembers() {
        initComponents();
        DefaultTableModel model;
        model = new DefaultTableModel();
        jTableMembers.setModel(model);
        model.addColumn("Codigo");
        model.addColumn("Nombre_usuario");
        model.addColumn("Apellido");
        model.addColumn("Cargo");
        model.addColumn("Correo");
        model.addColumn("Contraseña");
        model.addColumn("Respuesta");
        model.addColumn("Telefono");
        model.addColumn("Cedula");

        //jTableEquipment.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jTableMembers.getTableHeader().setReorderingAllowed(false);

        DaoUser equipmentDao = new DaoUser();
        equipmentDao.consultarMiembro(model);
        jScrollPane1.setViewportView(jTableMembers);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMembers = new javax.swing.JTable();

        jTableMembers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableMembers);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMembers;
    // End of variables declaration//GEN-END:variables
}
