package Form;

import Control.Control;
import Database_access.DaoEquipment;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ListEquipment extends javax.swing.JPanel {
    
    String select;
    String opc;
    String estado;
    int numEquipo;
    int marc;
    int key;
    Control control = new Control();

    public ListEquipment(int code) {
        key = code;
        initComponents();
        DefaultTableModel model;
        model = new DefaultTableModel();
        jTableEquipment.setModel(model);
        model.addColumn("Numero_equipo");
        model.addColumn("Nombre_equipo");
        //model.addColumn("Marca");
        //model.addColumn("Descripcion");
        //model.addColumn("Estado");

        //jTableEquipment.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jTableEquipment.getTableHeader().setReorderingAllowed(false);

        DaoEquipment equipmentDao = new DaoEquipment();
        equipmentDao.consultarEquipo(model);
        jScrollPane1.setViewportView(jTableEquipment);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opcion = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEquipment = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableConsulta = new javax.swing.JTable();
        jButtonInformation = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        reservar = new javax.swing.JRadioButton();
        solicitar = new javax.swing.JRadioButton();
        aceptar = new javax.swing.JButton();

        jTableEquipment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jTableEquipment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEquipmentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableEquipment);

        jTableConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Numero_equipo", "Nombre_equipo", "Marca", "Descripcion", "Estado"
            }
        ));
        jTableConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableConsultaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableConsulta);

        jButtonInformation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/dialog_information.png"))); // NOI18N
        jButtonInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInformationActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Información del Equipo consultado:");

        opcion.add(reservar);
        reservar.setText("Reservar");
        reservar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reservarMouseClicked(evt);
            }
        });
        reservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservarActionPerformed(evt);
            }
        });

        opcion.add(solicitar);
        solicitar.setText("Solicitar");
        solicitar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                solicitarMouseClicked(evt);
            }
        });
        solicitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solicitarActionPerformed(evt);
            }
        });

        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(solicitar)
                            .addComponent(jLabel1)
                            .addComponent(jButtonInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reservar)
                            .addComponent(aceptar))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(solicitar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reservar)
                .addGap(18, 18, 18)
                .addComponent(aceptar)
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTableEquipmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEquipmentMouseClicked
        int row = jTableEquipment.rowAtPoint(evt.getPoint());
        DefaultTableModel asd = (DefaultTableModel) jTableEquipment.getModel();
        String dato=String.valueOf(asd.getValueAt(jTableEquipment.getSelectedRow(), 0));
        select = dato;
        //select = Integer.toString(row+1);
        
        //JOptionPane.showMessageDialog(null, dato);
        //select = (String)jTableEquipment.getValueAt(row, 1);
        //select = (String)jTableEquipment.getValueAt(row, 0);
        modificar(); 
    }//GEN-LAST:event_jTableEquipmentMouseClicked

    private void modificar(){
        DefaultTableModel model;
        model = new DefaultTableModel();
        jTableConsulta.setModel(model);
        model.addColumn("Numero_equipo");
        model.addColumn("Nombre_equipo");
        model.addColumn("Marca");
        model.addColumn("Descripcion");
        model.addColumn("Estado");

        //jTableEquipment.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jTableConsulta.getTableHeader().setReorderingAllowed(false);

        DaoEquipment equipmentDao = new DaoEquipment();
        equipmentDao.consultarEquipo2(model, select);
        jScrollPane3.setViewportView(jTableConsulta);
    }
    
    private void jButtonInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInformationActionPerformed
        JOptionPane.showMessageDialog(null, "Para consultar un programa simplemente seleccione un equipo de la tabla de arriba.\n"
                + "Seguidamente seleccionelo en la tabla de abajo si desea el prestamo o reserva de este");
    }//GEN-LAST:event_jButtonInformationActionPerformed

    private void reservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reservarActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        DaoEquipment equipmentDao = new DaoEquipment();
        if(opc == solicitar.getLabel()){
            if(estado.equals("Disponible")){
                estado = "Prestado";
                equipmentDao.editarEquipo(estado, select);
                int numFilas = control.insertarPrestamo(key, numEquipo, marc);

        System.out.println("Filas " + numFilas);
        if (numFilas == 1) {

            JOptionPane.showMessageDialog(null, "Prestamo Guardado con Exito");
        } else {
            JOptionPane.showMessageDialog(null, "Ocurrio un problema al guardar el Equipo");
        }
            }else{
                if(estado.equals("Prestado")){
                   JOptionPane.showMessageDialog(null, "El equipo ya se encuentra en prestamo, proceda a reservarlo."); 
                }else{
                    if(estado.equals("Reservado")){
                        JOptionPane.showMessageDialog(null, "El equipo se encuentra reservado.");//pendiente crear reservas
                    }
                }
            }
        }else{
            if(opc == reservar.getLabel()){
                if(estado.equals("Prestado")){
                    estado = "Reservado";
                    equipmentDao.editarEquipo(estado, select);
                    JOptionPane.showMessageDialog(null, "Solicitud registrada.");
                }else{
                    if(estado.equals("Disponible")){
                         JOptionPane.showMessageDialog(null, "El equipo se encuentra disponible, proceda a solicitarlo.");
                    }else{
                        if(estado.equals("Reservado")){
                            JOptionPane.showMessageDialog(null, "El equipo ya se encuentra reservado.");
                        }
                    }
                }
            }
        }        
    }//GEN-LAST:event_aceptarActionPerformed

    private void solicitarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_solicitarMouseClicked
        opc = solicitar.getLabel();
    }//GEN-LAST:event_solicitarMouseClicked

    private void reservarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservarMouseClicked
        opc = reservar.getLabel();
    }//GEN-LAST:event_reservarMouseClicked

    private void jTableConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableConsultaMouseClicked
        
        DefaultTableModel asd = (DefaultTableModel) jTableConsulta.getModel();
        String dato=String.valueOf(asd.getValueAt(jTableConsulta.getSelectedRow(), 4));
        estado = dato;//Integer.parseInt(dato);
        numEquipo = Integer.parseInt(String.valueOf(asd.getValueAt(jTableConsulta.getSelectedRow(), 0)));
        marc = Integer.parseInt(String.valueOf(asd.getValueAt(jTableConsulta.getSelectedRow(), 2)));
        //JOptionPane.showMessageDialog(null, estado+" "+numEquipo+" "+ marc);
    }//GEN-LAST:event_jTableConsultaMouseClicked

    private void solicitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solicitarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_solicitarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JButton jButtonInformation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableConsulta;
    private javax.swing.JTable jTableEquipment;
    private javax.swing.ButtonGroup opcion;
    private javax.swing.JRadioButton reservar;
    private javax.swing.JRadioButton solicitar;
    // End of variables declaration//GEN-END:variables
}
